"""
Java enum code generator.

Converts a shared enum JSON definition into a Java enum class file,
targeting the com.example.android.enums package.
"""

from typing import Any


# The package all generated Java enums live under.
# Must stay in sync with the outputs.java path prefix in each shared/enums/*.json.
_JAVA_PACKAGE: str = "com.example.android.enums"


def generate(definition: dict[str, Any]) -> str:
    """Generate a Java enum source file from a JSON enum definition.

    Produces a ``public enum Foo`` with a typed constructor and a
    ``getValue()`` accessor, mirroring the JSON member list exactly.

    Args:
        definition: Parsed content of a shared/enums/*.json file.

    Returns:
        A fully-formed Java source string ready to be written to disk.

    Raises:
        KeyError: If required fields (``name``, ``type``, ``members``) are absent.
        ValueError: If ``definition["type"]`` is not ``"string"`` or ``"int"``.
    """
    enum_name: str = definition["name"]
    description: str = definition["description"]
    value_type: str = definition["type"]
    members: list[dict[str, Any]] = definition["members"]

    if value_type == "string":
        java_type: str = "String"
    elif value_type == "int":
        java_type = "int"
    else:
        raise ValueError(
            f"Unsupported enum value type: {value_type!r}. Expected 'string' or 'int'."
        )

    lines: list[str] = [
        "// This file is AUTO-GENERATED by shared/codegen/generate.py",
        "// DO NOT edit manually — edit shared/enums/*.json and re-run the generator.",
        "",
        f"package {_JAVA_PACKAGE};",
        "",
        "/**",
        f" * {description}",
        " */",
        f"public enum {enum_name} {{",
    ]

    for i, member in enumerate(members):
        member_name: str = member["name"]
        member_value: Any = member["value"]
        member_desc: str = member["description"]

        value_repr: str = f'"{member_value}"' if value_type == "string" else str(member_value)
        is_last: bool = i == len(members) - 1
        # Java enum entries end with ';' on the last entry, ',' otherwise.
        terminator: str = ";" if is_last else ","

        lines.append(f"    /** {member_desc} */")
        lines.append(f"    {member_name}({value_repr}){terminator}")

    # Append the typed constructor and getValue() accessor.
    lines.extend([
        "",
        f"    private final {java_type} value;",
        "",
        f"    {enum_name}({java_type} value) {{",
        "        this.value = value;",
        "    }",
        "",
        f"    public {java_type} getValue() {{",
        "        return value;",
        "    }",
        "}",
        "",
    ])

    return "\n".join(lines)
