"""
Kotlin enum code generator.

Converts a shared enum JSON definition into a Kotlin enum class file,
targeting the com.example.android.enums package.
"""

from typing import Any


# The package all generated Kotlin enums live under.
# Must stay in sync with the outputs.kotlin path prefix in each shared/enums/*.json.
_KOTLIN_PACKAGE: str = "com.example.android.enums"


def generate(definition: dict[str, Any]) -> str:
    """Generate a Kotlin enum class source file from a JSON enum definition.

    Produces an ``enum class Foo(val value: String)`` (or ``Int``) whose
    entries mirror the JSON member list exactly.

    Args:
        definition: Parsed content of a shared/enums/*.json file.

    Returns:
        A fully-formed Kotlin source string ready to be written to disk.

    Raises:
        KeyError: If required fields (``name``, ``type``, ``members``) are absent.
        ValueError: If ``definition["type"]`` is not ``"string"`` or ``"int"``.
    """
    enum_name: str = definition["name"]
    description: str = definition["description"]
    value_type: str = definition["type"]
    members: list[dict[str, Any]] = definition["members"]

    if value_type == "string":
        kotlin_type = "String"
    elif value_type == "int":
        kotlin_type = "Int"
    else:
        raise ValueError(
            f"Unsupported enum value type: {value_type!r}. Expected 'string' or 'int'."
        )

    lines: list[str] = [
        "// This file is AUTO-GENERATED by shared/codegen/generate.py",
        "// DO NOT edit manually — edit shared/enums/*.json and re-run the generator.",
        "",
        f"package {_KOTLIN_PACKAGE}",
        "",
        "/**",
        f" * {description}",
        " */",
        f"enum class {enum_name}(val value: {kotlin_type}) {{",
    ]

    for i, member in enumerate(members):
        member_name: str = member["name"]
        member_value: Any = member["value"]
        member_desc: str = member["description"]

        value_repr = f'"{member_value}"' if value_type == "string" else str(member_value)
        is_last = i == len(members) - 1
        terminator = ";" if is_last else ","

        lines.append(f"    /** {member_desc} */")
        lines.append(f"    {member_name}({value_repr}){terminator}")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)
