"""
Python enum code generator.

Converts a shared enum JSON definition into a Python StrEnum or IntEnum file.
"""

from typing import Any


def generate(definition: dict[str, Any]) -> str:
    """Generate a Python enum source file from a JSON enum definition.

    Produces a StrEnum for string-typed enums and an IntEnum for integer-typed
    enums, matching the conventions already used in desktop/enums/.

    Args:
        definition: Parsed content of a shared/enums/*.json file.

    Returns:
        A fully-formed Python source string ready to be written to disk.

    Raises:
        KeyError: If required fields (``name``, ``type``, ``members``) are absent.
        ValueError: If ``definition["type"]`` is not ``"string"`` or ``"int"``.
    """
    enum_name: str = definition["name"]
    description: str = definition["description"]
    value_type: str = definition["type"]
    members: list[dict[str, Any]] = definition["members"]

    if value_type == "string":
        base_class: str = "StrEnum"
    elif value_type == "int":
        base_class = "IntEnum"
    else:
        raise ValueError(
            f"Unsupported enum value type: {value_type!r}. Expected 'string' or 'int'."
        )
    import_line: str = f"from enum import {base_class}"

    # --- File header: auto-gen warning + import ---
    lines: list[str] = [
        "# This file is AUTO-GENERATED by shared/codegen/generate.py",
        "# DO NOT edit manually — edit shared/enums/*.json and re-run the generator.",
        "",
        import_line,
        "",
        "",
    ]

    # --- Class declaration with module-level docstring ---
    lines += [
        f"class {enum_name}({base_class}):",
        f'    """{description}"""',
        "",
    ]

    # --- Enum members: one comment + one assignment per member ---
    for member in members:
        member_name: str = member["name"]
        member_value: Any = member["value"]
        member_desc: str = member["description"]

        # Wrap string values in quotes; int values are emitted as-is.
        value_repr: str = f'"{member_value}"' if value_type == "string" else str(member_value)
        lines.append(f"    # {member_desc}")
        lines.append(f"    {member_name} = {value_repr}")
        lines.append("")

    return "\n".join(lines)
