// This file is AUTO-GENERATED by shared/codegen/generate.py
// DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

package com.example.android.enums;

/**
 * Per-file transfer result tokens written by the PC on BACKUP_FILE_RESULT channels. Both PC and Android must write and compare these exact strings — define them here once and generate both sides.
 */
public enum BackupFileResult {
    /** The file was received and saved (or correctly screened out) by the PC — the transfer itself completed without error. */
    SUCCESS("succ"),
    /** A transport/IO problem occurred while receiving or saving the file on the PC. */
    FAILURE("fail");

    private final String value;

    BackupFileResult(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
