// This file is AUTO-GENERATED by shared/codegen/generate.py
// DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

package com.example.android.enums

/**
 * TauSync named-stream identifiers. Both PC and Android must call tau.connect() with the exact same string — define it here once and generate both sides.
 */
enum class Channel(val value: String) {
    /** Stream for exchanging static device metadata (name, model, OS version). */
    DEVICE_INFO("device_info"),
    /** Stream for real-time battery level and charging-state updates. */
    BATTERY("battery"),
    /** Stream for storage usage statistics (total, used, free). */
    STORAGE("storage"),
    /** Stream for syncing the available tools/actions list. */
    TOOLS("tools");
}
