// This file is AUTO-GENERATED by shared/codegen/generate.py
// DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

package com.example.android.enums;

/**
 * TauSync meeting-word identifiers for the clipboard sync protocol. Both PC and Android must call tau.connect() with the exact same string — define it here once and generate both sides.
 */
public enum ClipboardChannels {
    /** Android sends clipboard content to PC. */
    CLIPBOARD_ANDROID_TO_PC("clipboard_android_to_pc"),
    /** PC sends clipboard content to Android. */
    CLIPBOARD_PC_TO_ANDROID("clipboard_pc_to_android");

    private final String value;

    ClipboardChannels(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
