// This file is AUTO-GENERATED by shared/codegen/generate.py
// DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

package com.example.android.enums;

/**
 * JSON key names for the DeviceInfo payload exchanged over the DEVICE_INFO channel. Both PC and Android must use the exact same key strings — define them here once and generate both sides.
 */
public enum DeviceInfoField {
    /** Unique device identifier. */
    ID("id"),
    /** Human-readable device name, e.g. "Pixel 8 Pro". */
    NAME("name"),
    /** OS version string, e.g. "Android 14". */
    OS_LABEL("os_label"),
    /** User-assigned label, e.g. "Home". */
    TAG("tag"),
    /** Current connection status of the device. */
    STATUS("status"),
    /** Human-readable recency string, e.g. "now", "today", "3 days ago". */
    LAST_SEEN("last_seen"),
    /** Battery level as an integer percentage (0–100). */
    BATTERY_PERCENTAGE("battery_percentage"),
    /** Whether the device is currently charging. */
    BATTERY_CHARGING("battery_charging"),
    /** Used storage in bytes. */
    STORAGE_USED("storage_used"),
    /** Total storage capacity in bytes. */
    STORAGE_TOTAL("storage_total"),
    /** Last known LAN IP address of the device, used to reconnect. */
    IP("ip");

    private final String value;

    DeviceInfoField(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
