// This file is AUTO-GENERATED by shared/codegen/generate.py
// DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

package com.example.android.enums;

/**
 * TauSync meeting-word identifiers for session lifecycle events. Both PC and Android must call tau.connect() with the exact same string — define it here once and generate both sides.
 */
public enum SessionChannels {
    /** Phone opens this channel when it initiates a disconnect. */
    DISCONNECT_FROM_PHONE("disconnect_phone"),
    /** PC opens this channel to notify the phone before a PC-initiated disconnect. */
    DISCONNECT_FROM_PC("disconnect_pc");

    private final String value;

    SessionChannels(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
