// This file is AUTO-GENERATED by shared/codegen/generate.py
// DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

package com.example.android.enums;

/**
 * TauSync meeting-word identifiers for the tool-enabled settings sync protocol. Both PC and Android must call tau.connect() with the exact same string — define it here once and generate both sides.
 */
public enum SettingsChannels {
    /** Android pushes its tool-enabled state to PC. */
    TOOLS_ANDROID_TO_PC("settings_tools_android_to_pc"),
    /** PC pushes its tool-enabled state to Android. */
    TOOLS_PC_TO_ANDROID("settings_tools_pc_to_android");

    private final String value;

    SettingsChannels(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
