// This file is AUTO-GENERATED by shared/codegen/generate.py
// DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

package com.example.android.enums;

/**
 * TauSync meeting-word identifiers for the virtual drive protocol. PC initiates all channels; Android responds. Both sides call tau.connect() with the exact same string.
 */
public enum VirtualDriveChannels {
    /** PC requests a directory listing at a given path. Fixed meeting word. */
    VIRTUAL_DRIVE_LIST("virtual_drive_list"),
    /** PC requests file or folder metadata (size, mtime, is_dir). Fixed meeting word. */
    VIRTUAL_DRIVE_STAT("virtual_drive_stat"),
    /** Base prefix for read sessions. Negotiation channel: PC sends {path, offset, length, uuid}; actual data flows on virtual_drive_read_{uuid}. */
    VIRTUAL_DRIVE_READ("virtual_drive_read"),
    /** Base prefix for write sessions. Negotiation channel: PC sends {path, uuid}; actual data streams on virtual_drive_write_{uuid}. */
    VIRTUAL_DRIVE_WRITE("virtual_drive_write"),
    /** PC requests creation of a file or directory. Fixed meeting word. */
    VIRTUAL_DRIVE_CREATE("virtual_drive_create"),
    /** PC requests deletion of a file or directory. Fixed meeting word. */
    VIRTUAL_DRIVE_DELETE("virtual_drive_delete"),
    /** PC requests rename or move of a file or directory. Fixed meeting word. */
    VIRTUAL_DRIVE_RENAME("virtual_drive_rename"),
    /** PC requests a file size change (truncate or extend). Fixed meeting word. */
    VIRTUAL_DRIVE_TRUNCATE("virtual_drive_truncate");

    private final String value;

    VirtualDriveChannels(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
