// This file is AUTO-GENERATED by shared/codegen/generate.py
// DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

package com.example.android.enums;

/**
 * TauSync meeting-word identifiers for the webcam streaming protocol. Android streams camera frames to PC over a persistent channel.
 */
public enum WebcamChannels {
    /** Android sends a start signal to PC. PC opens the virtual camera in response. */
    WEBCAM_START("webcam_start"),
    /** Android streams JPEG frames continuously to PC. Channel stays open for the duration of the session. */
    WEBCAM_FRAMES("webcam_frames");

    private final String value;

    WebcamChannels(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
