import datetime
from types import TracebackType
from typing import Optional, Type

class ServerNamedPipe:
    def __init__(self, input_buffer_size: int, output_buffer_size: int, pipe_name: str): ...

    def wait_for_client(self, timeout: datetime.timedelta | None = None) -> None: ...

    def read(self, timeout: datetime.timedelta | None = None) -> str: ...

    def close(self) -> None: ...

    def disconnect(self) -> None: ...

    def __enter__(self) -> 'ServerNamedPipe': ...

    def __exit__(self,
                 exc_type: Type[BaseException] | None,
                 exc_val: BaseException | None,
                 exc_tb: TracebackType | None) -> None: ...


class ClientNamedPipe:
    def __init__(self, input_buffer_size: int, output_buffer_size: int, pipe_name: str): ...

    def write(self, data: bytes, timeout: datetime.timedelta | None = None) -> None: ...

    def close(self) -> None: ...

    def __enter__(self) -> 'ClientNamedPipe': ...

    def __exit__(self,
                 exc_type: Optional[Type[BaseException]],
                 exc_val: Optional[BaseException],
                 exc_tb: Optional[TracebackType]) -> None: ...
