# This file is AUTO-GENERATED by shared/codegen/generate.py
# DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

from enum import StrEnum


class DeviceInfoChannels(StrEnum):
    """JSON key names for the DeviceInfo payload exchanged over the DEVICE_INFO channel. Both PC and Android must use the exact same key strings — define them here once and generate both sides."""

    # Unique device identifier.
    ID = "id"

    # Human-readable device name, e.g. "Pixel 8 Pro".
    NAME = "name"

    # OS version string, e.g. "Android 14".
    OS = "os"

    # User-assigned label, e.g. "Home".
    TAG = "tag"

    # Human-readable recency string, e.g. "now", "today", "3 days ago".
    LAST_SEEN = "last_seen"

    # Battery level as an integer percentage (0–100).
    BATTERY_LEVEL = "battery_level"

    # Whether the device is currently charging.
    BATTERY_CHARGING = "battery_charging"

    # Used storage in bytes.
    STORAGE_USED = "storage_used"

    # Total storage capacity in bytes.
    STORAGE_TOTAL = "storage_total"

    # Last known LAN IP address of the device, used to reconnect.
    IP = "ip"

    # The human-readable name of the Windows PC.
    PC_NAME = "pc_name"

    # The Windows version and build.
    PC_OS = "pc_os"

    # The active network interface type (e.g., Wi-Fi, Ethernet).
    CONNECTION_TYPE = "connection_type"
