name: TauSync Action

description: Build Windows DLL using Docker Compose

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4

    - name: Build windows DLL
      shell: bash
      run: dotnet publish TauSync/TauSync.Lib -c Release -o /output