[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tausync-py"
version = "0.1.0"
description = "TauSync Python SDK"
readme = "tausync_py/README.md"
requires-python = ">=3.9"
dependencies = [
    "pythonnet>=3.0.0",
]

[tool.setuptools]
packages = ["tausync_py"]

[tool.setuptools.package-data]
tausync_py = ["dll/*", "README.md"]

