services:
    tausync:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tausync
        restart: unless-stopped
        volumes:
        - ./TauSync_Windows/Tausync.Lib:/windows-build