# This file is AUTO-GENERATED by shared/codegen/generate.py
# DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

from enum import StrEnum


class BackupChannels(StrEnum):
    """TauSync meeting-word identifiers for the Android-to-PC backup protocol. Both PC and Android must call tau.connect() with the exact same string — define it here once and generate both sides."""

    # Android sends {num_files, total_size_bytes} as a lightweight header so the PC can display the transfer summary before the user picks a destination folder.
    BACKUP_MANIFEST_FROM_ANDROID = "backup_manifest"

    # PC sends a ready ack after the user confirms the destination folder.
    BACKUP_READY_FROM_PC = "backup_ready_pc"

    # Per-file channel prefix. Full channel name: BACKUP_FILE_SLOT + str(slot_index). Slot index matches the scan order.
    BACKUP_FILE_SLOT = "backup_slot_"

    # PC sends per-file transfer result to Android after receiving and attempting to save the file. Prefix — append slot index. Payload: one of BackupFileResult's values ("succ" | "fail"). "fail" indicates a transport/IO problem; PC-local screening rejections (corrupt/duplicate/filtered) are reported as "succ" since the transfer itself completed.
    BACKUP_FILE_RESULT = "backup_file_result_"

    # PC sends JSON control commands to Android during an active backup session. Payload: {"cmd": "pause"} | {"cmd": "resume"} | {"cmd": "stop"}. One connect() per command.
    BACKUP_CONTROL_FROM_PC = "backup_ctrl_pc"

    # Android sends JSON control commands to PC during an active backup session. Payload: {"cmd": "pause"} | {"cmd": "resume"} | {"cmd": "stop"}. One connect() per command.
    BACKUP_CONTROL_FROM_ANDROID = "backup_ctrl_android"
