# This file is AUTO-GENERATED by shared/codegen/generate.py
# DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

from enum import StrEnum


class ClipboardChannels(StrEnum):
    """TauSync meeting-word identifiers for the clipboard sync protocol. Both PC and Android must call tau.connect() with the exact same string — define it here once and generate both sides."""

    # Android sends clipboard content to PC.
    CLIPBOARD_ANDROID_TO_PC = "clipboard_android_to_pc"

    # PC sends clipboard content to Android.
    CLIPBOARD_PC_TO_ANDROID = "clipboard_pc_to_android"
