# This file is AUTO-GENERATED by shared/codegen/generate.py
# DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

from enum import StrEnum


class FileTransferChannels(StrEnum):
    """TauSync meeting-word identifiers for the file transfer protocol. Both PC and Android must call tau.connect() with the exact same string — define it here once and generate both sides."""

    # Metadata channel for a regular file transfer — carries JSON with the filename and byte-count before the data channel opens.
    REGULAR_FILE_METADATA = "file_meta"

    # Data channel for a regular file transfer — carries raw file bytes, exactly the byte-count declared in the metadata channel.
    REGULAR_FILE_DATA = "file_data"
