# This file is AUTO-GENERATED by shared/codegen/generate.py
# DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

from enum import StrEnum


class FileTransferResponse(StrEnum):
    """Accepted/rejected tokens exchanged over the REGULAR_FILE_RESPONSE channel. Both PC and Android must write and compare these exact strings — define them here once and generate both sides."""

    # Receiver accepted the incoming file — sender may open REGULAR_FILE_DATA and stream bytes.
    ACCEPTED = "accept"

    # Receiver rejected the incoming file — sender must abort without opening REGULAR_FILE_DATA.
    REJECTED = "reject"
