# This file is AUTO-GENERATED by shared/codegen/generate.py
# DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

from enum import StrEnum


class SessionChannels(StrEnum):
    """TauSync meeting-word identifiers for session lifecycle events. Both PC and Android must call tau.connect() with the exact same string — define it here once and generate both sides."""

    # Phone opens this channel when it initiates a disconnect.
    DISCONNECT_FROM_PHONE = "disconnect_phone"

    # PC opens this channel to notify the phone before a PC-initiated disconnect.
    DISCONNECT_FROM_PC = "disconnect_pc"

    # PC opens this channel right after the transport handshake and waits for the phone's reply. Answering it is what makes the session established on BOTH sides: only then does the PC emit device_connected and remember the phone, and only then does the phone remember the PC. An unanswered hello means the phone is gone (half-open link) and the PC re-listens instead of sitting connected to nobody.
    SESSION_HELLO = "session_hello"
