# This file is AUTO-GENERATED by shared/codegen/generate.py
# DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

from enum import StrEnum


class SettingsChannels(StrEnum):
    """TauSync meeting-word identifiers for the tool-enabled settings sync protocol. Both PC and Android must call tau.connect() with the exact same string — define it here once and generate both sides."""

    # Android pushes its tool-enabled state to PC.
    TOOLS_ANDROID_TO_PC = "settings_tools_android_to_pc"

    # PC pushes its tool-enabled state to Android.
    TOOLS_PC_TO_ANDROID = "settings_tools_pc_to_android"
