# This file is AUTO-GENERATED by shared/codegen/generate.py
# DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

from enum import StrEnum


class VirtualDriveChannels(StrEnum):
    """TauSync meeting-word identifiers for the virtual drive protocol. PC initiates all channels; Android responds. Both sides call tau.connect() with the exact same string."""

    # Base prefix for directory listing ops. Meeting word: virtual_drive_list_{uuid8}. PC sends {path}; Android responds with entries array.
    VIRTUAL_DRIVE_LIST = "virtual_drive_list"

    # Base prefix for metadata (stat) ops. Meeting word: virtual_drive_stat_{uuid8}. PC sends {path}; Android responds with entry fields.
    VIRTUAL_DRIVE_STAT = "virtual_drive_stat"

    # Base prefix for read ops. Meeting word: virtual_drive_read_{uuid8}. PC sends {path, offset, length}\n; Android streams file bytes back then closes.
    VIRTUAL_DRIVE_READ = "virtual_drive_read"

    # Base prefix for write sessions. Meeting word: virtual_drive_write_{uuid8}. PC sends {path}\n header then streams bytes until channel close; Android stores to temp file then finalizes.
    VIRTUAL_DRIVE_WRITE = "virtual_drive_write"

    # Base prefix for create ops. Meeting word: virtual_drive_create_{uuid8}. PC sends {path, is_dir}; Android creates file or directory.
    VIRTUAL_DRIVE_CREATE = "virtual_drive_create"

    # Base prefix for delete ops. Meeting word: virtual_drive_delete_{uuid8}. PC sends {path}; Android deletes file or directory.
    VIRTUAL_DRIVE_DELETE = "virtual_drive_delete"

    # Base prefix for rename ops. Meeting word: virtual_drive_rename_{uuid8}. PC sends {from, to}; Android renames or moves the entry.
    VIRTUAL_DRIVE_RENAME = "virtual_drive_rename"

    # Base prefix for truncate ops. Meeting word: virtual_drive_truncate_{uuid8}. PC sends {path, new_size}; Android resizes the file.
    VIRTUAL_DRIVE_TRUNCATE = "virtual_drive_truncate"

    # Base prefix for paginated listing ops. Meeting word: virtual_drive_list_page_{uuid8}. PC sends {path, after, limit}; Android responds with {ok, entries, has_more, next_after}. Entries are sorted by name; 'after' is the last name received (null for first page).
    VIRTUAL_DRIVE_LIST_PAGE = "virtual_drive_list_page"

    # Base prefix for full-directory enumeration. Meeting word: virtual_drive_list_full_{uuid8}. PC sends {path}; Android responds with {ok, dir_mtime_ms, entries} containing every child entry in one streamed response. The PC caches the listing under a short TTL (ListingCache) and serves all list_page requests of one enumeration locally, so a folder costs one round-trip rather than one per page; mutating ops evict the affected directories. dir_mtime_ms is recorded but not used to decide freshness: it arrives with the listing (so revalidating costs as much as refetching) and a directory's mtime does not change when a child is rewritten in place.
    VIRTUAL_DRIVE_LIST_FULL = "virtual_drive_list_full"
