# This file is AUTO-GENERATED by shared/codegen/generate.py
# DO NOT edit manually — edit shared/enums/*.json and re-run the generator.

from enum import StrEnum


class WebcamChannels(StrEnum):
    """TauSync meeting-word identifiers for the webcam streaming protocol. Android streams camera frames to PC over a persistent channel."""

    # Android sends a start signal to PC. PC opens the virtual camera in response.
    WEBCAM_START = "webcam_start"

    # Android streams JPEG frames continuously to PC. Channel stays open for the duration of the session.
    WEBCAM_FRAMES = "webcam_frames"
