from types import TracebackType
from typing import Any, Optional, Type


class ServerNamedPipe:
    def __init__(self, input_buffer_size: int, output_buffer_size: int, pipe_name: str): ...

    def wait_for_client(self) -> None: ...

    def read(self) -> str: ...

    def close(self) -> None: ...

    def disconnect(self) -> None: ...

    def __enter__(self) -> 'ServerNamedPipe': ...

    def __exit__(self,
                 exc_type: Optional[Type[BaseException]],
                 exc_val: Optional[BaseException],
                 exc_tb: Optional[TracebackType]) -> None: ...


class ClientNamedPipe:
    def __init__(self, input_buffer_size: int, output_buffer_size: int, pipe_name: str): ...

    def write(self, data: bytes) -> None: ...

    def close(self) -> None: ...
