name: Desktop

on:
  push:
    branches: ["**"]
    tags:
      - "v*"
jobs:


  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/tau_sync


      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r TauSync/windows/requirements.txt
          pip install -r desktop/requirements.txt
          pip install  TauSync/windows
          pip install pytest

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build native
        run: |
          cmake -S desktop/native/windows/pipe -B desktop/native/windows/pipe/build
          cmake --build desktop/native/windows/pipe/build --config Release
      - name: Copy file
        run: |
          Copy-Item `
          desktop/native/windows/pipe/build/Release/pipe_module.cp313-win_amd64.pyd `
          desktop/native/windows/pipe/

      - name: Run tests
        run: pytest desktop/


  build:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tau_sync

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build native
        run: |
          cmake -S desktop/native/windows/pipe -B desktop/native/windows/pipe/build
          cmake --build desktop/native/windows/pipe/build --config Release

      - name: Copy file
        run: |
          Copy-Item `
          desktop/native/windows/pipe/build/Release/pipe_module.cp313-win_amd64.pyd `
          desktop/native/windows/pipe/

      - name: Install deps
        run: |
          pip install -r TauSync/windows/requirements.txt
          pip install -r desktop/requirements.txt
          pip install  TauSync/windows
          pip install pyinstaller

      - name: Build EXEs
        run: |
          pyinstaller desktop/installer/Package/specs/file_handler.spec
          pyinstaller desktop/installer/Package/specs/main_app.spec

      - name: Build installer
        run: dotnet build desktop/installer/Bundle/ -c Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: |
            desktop/installer/**/bin/Release/*.exe


  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    environment: production

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: installer
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: artifacts/**/*.msi




